### ISSUE TITLE
hang when downloading `package:module_profile`

### ISSUE THREAD

**Issue by pq** [pq/pub_crawl#3]
reported by @Hixie:

> pub_crawl hung when i got to https://pub.dev/packages/module_profile
> until i killed the dart subprocess
> at which point it said something about a russian version of pub

**Comment by ditman** [comment]
I got this as well, pub get wouldn't work on that package either. I had to remove it from my surveys.

**Comment by pq** [comment]
Thanks, yeah.  It would be great to make this more robust.  Out of curiosity @ditman, have you seen similar hangs on other packages?  How much of an outlier is this one?

**Comment by ditman** [comment]
I don't think this is an issue with pub_crawl, as I said, that package fails even with a raw `pub get`. Other than having a timeout for the install process, I don't know how you could make this more robust!

This was the only package I saw of all the "flutter" ones that hangs (as of ~Sept '19). Maybe it needs to be removed from pub.dev?

I might have to pub_crawl some more soon to download packages again (I'll try and see if I can add the timeout and submit a PR)

**Comment by pq** [comment]
Super.  Thanks!

**Comment by pq** [comment]
> This was the only package I saw of all the "flutter" ones that hangs (as of ~Sept '19). Maybe it needs to be removed from pub.dev?

/fyi @jonasfj

**Comment by ditman** [comment]
We just landed a fix on the tool to avoid this, by adding a timeout (in seconds) to the "install dependencies" step. By running fetch like this:

```
dart ./pub_crawl/bin/pub_crawl.dart fetch --criteria flutter --max 100000 --timeout 600
```

When it encounters the package above, it'll chug for 10 minutes and then:

```
Extracted third_party/cache/module_profile-0.0.1
Installing dependencies for module_profile
Exception: Process with PID 158471 took longer than 600s to complete. Killed.
```

Then the crawl should continue with the rest of the packages.

More info in `pub_crawl fetch --help`:

> ```
> $ dart bin/pub_crawl.dart fetch --help
> fetch packages.
> 
> Usage: pub_crawl fetch [arguments]
> -h, --help                           Print this usage information.
> -c, --criteria=<crit_1,..,crit_n>    
> -m, --max=<packages>                 number of packages to download.
>                                      (defaults to "10")
> 
>     --timeout=<seconds>              time allotted for the download of each package.
>                                      (defaults to "disabled")
> 
>     --[no-]install                   install dependencies.
>                                      (defaults to on)
> 
>     --verbose                        show verbose output.
> ```

By default, no timeout is applied.

**Comment by pq** [comment]
Cheers @ditman!

**Comment by jonasfj** [comment]
I took a look at `package:module_profile` it has dependencies on a custom pub server, which we do not allow anymore. Also this custom pub server does not exist either.

**Comment by pq** [comment]
Thanks @jonasfj!

Is that why it's marked discontinued?

![image](https://user-images.githubusercontent.com/67586/68593301-f7847c00-0449-11ea-807d-c94229f43ce9.png)

**Comment by jonasfj** [comment]
No I think the author did that on their own.. maybe for this reason.. who knows..
